id: DSAR Inventa Handler
version: -1
name: DSAR Inventa Handler
description: Handling DSAR requests
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: ebf0ff3b-0bb6-44f1-8500-028313fbb5f4
    type: start
    task:
      id: ebf0ff3b-0bb6-44f1-8500-028313fbb5f4
      version: -1
      name: ''
      description: Entry point
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '31'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": -60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '9':
    id: '9'
    taskid: 9064b2b8-c337-4926-8692-5d8a5fa4aa4f
    type: regular
    task:
      id: 9064b2b8-c337-4926-8692-5d8a5fa4aa4f
      version: -1
      name: get piis
      description: Get PII details from daatasubjest
      script: '|||inventa-get-sources-piis'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '27'
    scriptarguments:
      execution-timeout:
        simple: '10'
      retry-count:
        simple: '3'
      retry-interval:
        simple: '5'
      datasubject_id:
        simple: ${Inventa.DataSubjects.datasubject_id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 670,
          "y": 1140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: PII Entities
      output:
        simple: ${Inventa.DSAR.piis}
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '15':
    id: '15'
    taskid: 2c383620-cd29-4880-8854-26a821c09641
    type: title
    task:
      id: 2c383620-cd29-4880-8854-26a821c09641
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '20':
    id: '20'
    taskid: 5cbd8abb-9cea-4099-83d5-4e647c86c137
    type: regular
    task:
      id: 5cbd8abb-9cea-4099-83d5-4e647c86c137
      version: -1
      name: Link
      description: commands.local.cmd.linkIncidents
      script: Builtin|||linkIncidents
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - '29'
    scriptarguments:
      incidentId:
        simple: ${incident.id}
      linkedIncidentIDs:
        complex:
          root: foundIncidents.id
          filters:
          - - operator: isNotEqualString
              left:
                value:
                  simple: foundIncidents.id
                iscontext: true
              right:
                value:
                  simple: ${incident.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 870,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '21':
    id: '21'
    taskid: 2e786200-a4f2-4016-8210-76f8c6d68b5f
    type: regular
    task:
      id: 2e786200-a4f2-4016-8210-76f8c6d68b5f
      version: -1
      name: Find related incidents
      description: Searches Demisto incidents
      scriptName: SearchIncidentsV2
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '30'
    scriptarguments:
      query:
        simple: inventadsardatasubjectid:${incident.inventadsardatasubjectid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '27':
    id: '27'
    taskid: 444210fe-04c6-4678-8047-7249b65911dd
    type: regular
    task:
      id: 444210fe-04c6-4678-8047-7249b65911dd
      version: -1
      name: PIIs to Grid
      description: Creates a Grid table from items or key-value pairs.
      scriptName: SetGridField
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      columns:
        simple: piis
      context_path:
        simple: Inventa.Sources.piis
      grid_id:
        simple: inventadsarpiientities
      keys:
        simple: piis
      sort_by:
        simple: id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 670,
          "y": 1290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '29':
    id: '29'
    taskid: eed298fb-4670-489a-8c49-cc866ed77f41
    type: title
    task:
      id: eed298fb-4670-489a-8c49-cc866ed77f41
      version: -1
      name: Handle Context
      description: Handle Context
      type: title
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '9'
      - '33'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '30':
    id: '30'
    taskid: 4cb712ac-6be2-4d3c-85db-17e72a42b89e
    type: condition
    task:
      id: 4cb712ac-6be2-4d3c-85db-17e72a42b89e
      version: -1
      name: Check if related incidents list is empty
      description: Check if related incidents found
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '20'
      yes:
      - '29'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: hasLength
          left:
            value:
              complex:
                root: foundIncidents.id
                filters:
                - - operator: isNotEqualString
                    left:
                      value:
                        simple: foundIncidents.id
                      iscontext: true
                    right:
                      value:
                        simple: ${incident.id}
            iscontext: true
          right:
            value:
              simple: '0'
    view: |-
      {
        "position": {
          "x": 470,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '31':
    id: '31'
    taskid: 4c52dec9-eedf-4d3c-85a4-0b4c770cf6b2
    type: regular
    task:
      id: 4c52dec9-eedf-4d3c-85a4-0b4c770cf6b2
      version: -1
      name: Validate Inputs
      description: Validates incident's inputs
      script: '|||inventa-validate-incident-inputs'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '35'
    scriptarguments:
      birthday:
        simple: ${incident.inventabirthday}
      cc_number:
        simple: ${incident.inventacreditcardnumber}
      city:
        simple: ${incident.city}
      datasubject_id:
        simple: ${incident.inventadsardatasubjectid}
      driver_license:
        simple: ${incident.inventadriverlicense}
      full_name:
        simple: ${incident.inventafullname}
      given_name:
        simple: ${incident.givenname}
      national_id:
        simple: ${incident.inventanationalid}
      passport_number:
        simple: ${incident.inventapassportnumber}
      phone_number:
        simple: ${incident.phonenumber}
      reason:
        simple: ${incident.inventareportreason}
      street_address:
        simple: ${incident.streetaddress}
      surname:
        simple: ${incident.surname}
      tax_id:
        simple: ${incident.inventataxid}
      ticket_id:
        simple: ${incident.inventadsarinventaticket}
      vehicle_number:
        simple: ${incident.inventavehiclenumber}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 90
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '33':
    id: '33'
    taskid: de7118b3-b5f0-4429-8bf5-06eb7d5fb32c
    type: regular
    task:
      id: de7118b3-b5f0-4429-8bf5-06eb7d5fb32c
      version: -1
      name: Get sources
      description: Get sources details
      script: Inventa|||inventa-get-sources
      type: regular
      iscommand: true
      brand: Inventa
    nexttasks:
      '#none#':
      - '34'
    scriptarguments:
      datasubject_id:
        simple: ${Inventa.DataSubjects.datasubject_id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 270,
          "y": 1140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '34':
    id: '34'
    taskid: c244b5dd-d03c-4d3c-8d20-7b017e532b17
    type: regular
    task:
      id: c244b5dd-d03c-4d3c-8d20-7b017e532b17
      version: -1
      name: Sources to Grid
      description: Creates a Grid table from items or key-value pairs.
      scriptName: SetGridField
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      columns:
        simple: id, applianceName, timestamp, keyType, path, url, hostName, dbName, vendor, type, entityTypes, content
      context_path:
        simple: Inventa.Sources.sources
      grid_id:
        simple: inventasource
      keys:
        simple: id, applianceName, timestamp, keyType, path, url, hostName, dbName, vendor, type, entityTypes, content
      sort_by:
        simple: id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 270,
          "y": 1290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '35':
    id: '35'
    taskid: cad99c88-0733-428a-8a60-e0f0091d0c46
    type: regular
    task:
      id: cad99c88-0733-428a-8a60-e0f0091d0c46
      version: -1
      name: DataSubject id
      description: Retrieves ID of a data subject from passed constraints
      script: '|||inventa-get-datasubject-id'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '21'
    scriptarguments:
      birthday:
        simple: ${inputs.Birthday}
      cc_number:
        simple: ${inputs.Credit Card Number}
      city:
        simple: ${inputs.City}
      driver_license:
        simple: ${inputs.Driver License}
      full_name:
        simple: ${inputs.Full Name}
      given_name:
        simple: ${inputs.First Name}
      national_id:
        simple: ${inputs.National ID}
      passport_number:
        simple: ${inputs.Passport Number}
      phone_number:
        simple: ${inputs.Phone Number}
      street_address:
        simple: ${inputs.Street Address}
      surname:
        simple: ${inputs.Surname}
      tax_id:
        simple: ${inputs.Tax ID}
      vehicle_number:
        simple: ${inputs.Vehicle Number}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1595,
        "width": 980,
        "x": 270,
        "y": -60
      }
    }
  }
inputs:
- key: National ID
  value:
    simple: ${incident.inventanationalid}
  required: false
  description: ''
  playbookInputQuery:
- key: Passport Number
  value:
    simple: ${incident.inventapassportnumber}
  required: false
  description: ''
  playbookInputQuery:
- key: Driver License
  value:
    simple: ${incident.inventadriverlicense}
  required: false
  description: ''
  playbookInputQuery:
- key: Tax ID
  value:
    simple: ${incident.inventataxid}
  required: false
  description: ''
  playbookInputQuery:
- key: Credit Card Number
  value:
    simple: ${incident.inventacreditcardnumber}
  required: false
  description: ''
  playbookInputQuery:
- key: First Name
  value:
    simple: ${incident.firstname}
  required: false
  description: ''
  playbookInputQuery:
- key: Surname
  value:
    simple: ${incident.surname}
  required: false
  description: ''
  playbookInputQuery:
- key: Full Name
  value:
    simple: ${incident.inventafullname}
  required: false
  description: ''
  playbookInputQuery:
- key: Vehicle Number
  value:
    simple: ${incident.inventavehiclenumber}
  required: false
  description: ''
  playbookInputQuery:
- key: Phone Number
  value:
    simple: ${incident.phonenumber}
  required: false
  description: ''
  playbookInputQuery:
- key: Birthday
  value:
    simple: ${incident.inventabirthday}
  required: false
  description: ''
  playbookInputQuery:
- key: City
  value:
    simple: ${incident.city}
  required: false
  description: ''
  playbookInputQuery:
- key: Street Address
  value:
    simple: ${incident.streetaddress}
  required: false
  description: ''
  playbookInputQuery:
- key: Reason
  value:
    simple: ${incident.inventadsarreportreason}
  required: false
  description: ''
  playbookInputQuery:
- key: Ticket
  value:
    simple: ${incident.inventadsarinventaticket}
  required: false
  description: ''
  playbookInputQuery:
outputs:
- contextPath: Inventa.PiiEntities.entities
  description: entities for certain PII
tests:
- No tests (auto formatted)
fromversion: 6.0.0
