description: Handling DSAR requests
id: DSAR Inventa Handler
inputs:
- description: ''
  key: National ID
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.inventanationalid}
- description: ''
  key: Passport Number
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.inventapassportnumber}
- description: ''
  key: Driver License
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.inventadriverlicense}
- description: ''
  key: Tax ID
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.inventataxid}
- description: ''
  key: Credit Card Number
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.inventacreditcardnumber}
- description: ''
  key: First Name
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.firstname}
- description: ''
  key: Surname
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.surname}
- description: ''
  key: Full Name
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.inventafullname}
- description: ''
  key: Vehicle Number
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.inventavehiclenumber}
- description: ''
  key: Phone Number
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.phonenumber}
- description: ''
  key: Birthday
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.inventabirthday}
- description: ''
  key: City
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.city}
- description: ''
  key: Street Address
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.streetaddress}
- description: ''
  key: Reason
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.inventadsarreportreason}
- description: ''
  key: Ticket
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.inventadsarinventaticket}
name: DSAR Inventa Handler
outputs:
- contextPath: Inventa.PiiEntities.entities
  description: entities for certain PII
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '31'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Entry point
      id: 96f1e94d-c4ff-42a8-8c2b-6097d39f2554
      iscommand: false
      name: ''
      version: -1
    taskid: 96f1e94d-c4ff-42a8-8c2b-6097d39f2554
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 470,
          "y": -60
        }
      }
  '9':
    fieldMapping:
    - incidentfield: PII Entities
      output:
        simple: ${Inventa.DSAR.piis}
    id: '9'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '27'
    note: false
    quietmode: 0
    scriptarguments:
      datasubject_id:
        simple: ${Inventa.DataSubjects.datasubject_id}
      execution-timeout:
        simple: '10'
      retry-count:
        simple: '3'
      retry-interval:
        simple: '5'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Get PII details from daatasubjest
      id: b7a1f30d-123b-4f85-8150-30d47ab74773
      iscommand: true
      name: get piis
      script: '|||inventa-get-sources-piis'
      type: regular
      version: -1
    taskid: b7a1f30d-123b-4f85-8150-30d47ab74773
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 670,
          "y": 1140
        }
      }
  '15':
    id: '15'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Done
      id: cfad5f5b-a50e-4b9d-8e03-5ba8d110d65b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: cfad5f5b-a50e-4b9d-8e03-5ba8d110d65b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1470
        }
      }
  '20':
    id: '20'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '29'
    note: false
    quietmode: 0
    scriptarguments:
      incidentId:
        simple: ${incident.id}
      linkedIncidentIDs:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: foundIncidents.id
              operator: isNotEqualString
              right:
                value:
                  simple: ${incident.id}
          root: foundIncidents.id
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.linkIncidents
      id: 4455e5ce-cd5f-4bbb-8758-6af90c019c42
      iscommand: true
      name: Link
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: 4455e5ce-cd5f-4bbb-8758-6af90c019c42
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 820
        }
      }
  '21':
    id: '21'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '30'
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: inventadsardatasubjectid:${incident.inventadsardatasubjectid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Searches Demisto incidents
      id: 76df508d-e7cd-4b8f-8067-3aba6449cdc8
      iscommand: false
      name: Find related incidents
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: 76df508d-e7cd-4b8f-8067-3aba6449cdc8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 490
        }
      }
  '27':
    id: '27'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    quietmode: 0
    scriptarguments:
      columns:
        simple: piis
      context_path:
        simple: Inventa.Sources.piis
      grid_id:
        simple: inventadsarpiientities
      keys:
        simple: piis
      sort_by:
        simple: id
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Creates a Grid table from items or key-value pairs.
      id: 4c97f145-0efd-4ad8-805d-9b42a8a3c961
      iscommand: false
      name: PIIs to Grid
      script: SetGridField
      type: regular
      version: -1
    taskid: 4c97f145-0efd-4ad8-805d-9b42a8a3c961
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 670,
          "y": 1290
        }
      }
  '29':
    id: '29'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '9'
      - '33'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Handle Context
      id: e1b2ff70-cd0f-4f77-87e4-6ca4f32827a0
      iscommand: false
      name: Handle Context
      type: title
      version: -1
    taskid: e1b2ff70-cd0f-4f77-87e4-6ca4f32827a0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 470,
          "y": 990
        }
      }
  '30':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: foundIncidents.id
                    operator: isNotEqualString
                    right:
                      value:
                        simple: ${incident.id}
                root: foundIncidents.id
          operator: hasLength
          right:
            value:
              simple: '0'
      label: yes
    id: '30'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - '20'
      yes:
      - '29'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check if related incidents found
      id: 52723e3c-a176-4621-8947-bd99ba9b4d37
      iscommand: false
      name: Check if related incidents list is empty
      type: condition
      version: -1
    taskid: 52723e3c-a176-4621-8947-bd99ba9b4d37
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 470,
          "y": 650
        }
      }
  '31':
    id: '31'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '35'
    note: false
    quietmode: 0
    scriptarguments:
      birthday:
        simple: ${incident.inventabirthday}
      cc_number:
        simple: ${incident.inventacreditcardnumber}
      city:
        simple: ${incident.city}
      datasubject_id:
        simple: ${incident.inventadsardatasubjectid}
      driver_license:
        simple: ${incident.inventadriverlicense}
      full_name:
        simple: ${incident.inventafullname}
      given_name:
        simple: ${incident.givenname}
      national_id:
        simple: ${incident.inventanationalid}
      passport_number:
        simple: ${incident.inventapassportnumber}
      phone_number:
        simple: ${incident.phonenumber}
      reason:
        simple: ${incident.inventareportreason}
      street_address:
        simple: ${incident.streetaddress}
      surname:
        simple: ${incident.surname}
      tax_id:
        simple: ${incident.inventataxid}
      ticket_id:
        simple: ${incident.inventadsarinventaticket}
      vehicle_number:
        simple: ${incident.inventavehiclenumber}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Validates incident's inputs
      id: e9d37d6c-6923-4297-8ca1-930e38eb4a64
      iscommand: true
      name: Validate Inputs
      script: '|||inventa-validate-incident-inputs'
      type: regular
      version: -1
    taskid: e9d37d6c-6923-4297-8ca1-930e38eb4a64
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 90
        }
      }
  '33':
    id: '33'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '34'
    note: false
    quietmode: 0
    scriptarguments:
      datasubject_id:
        simple: ${Inventa.DataSubjects.datasubject_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Inventa
      description: Get sources details
      id: 37232ded-7714-40e3-8a64-8e9effcf6102
      iscommand: true
      name: Get sources
      script: Inventa|||inventa-get-sources
      type: regular
      version: -1
    taskid: 37232ded-7714-40e3-8a64-8e9effcf6102
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 270,
          "y": 1140
        }
      }
  '34':
    id: '34'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    quietmode: 0
    scriptarguments:
      columns:
        simple: id, applianceName, timestamp, keyType, path, url, hostName, dbName, vendor, type, entityTypes, content
      context_path:
        simple: Inventa.Sources.sources
      grid_id:
        simple: inventasource
      keys:
        simple: id, applianceName, timestamp, keyType, path, url, hostName, dbName, vendor, type, entityTypes, content
      sort_by:
        simple: id
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Creates a Grid table from items or key-value pairs.
      id: 9244aa3b-db6e-4870-8def-bed71562bf32
      iscommand: false
      name: Sources to Grid
      script: SetGridField
      type: regular
      version: -1
    taskid: 9244aa3b-db6e-4870-8def-bed71562bf32
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 270,
          "y": 1290
        }
      }
  '35':
    id: '35'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '21'
    note: false
    quietmode: 0
    scriptarguments:
      birthday:
        simple: ${inputs.Birthday}
      cc_number:
        simple: ${inputs.Credit Card Number}
      city:
        simple: ${inputs.City}
      driver_license:
        simple: ${inputs.Driver License}
      full_name:
        simple: ${inputs.Full Name}
      given_name:
        simple: ${inputs.First Name}
      national_id:
        simple: ${inputs.National ID}
      passport_number:
        simple: ${inputs.Passport Number}
      phone_number:
        simple: ${inputs.Phone Number}
      street_address:
        simple: ${inputs.Street Address}
      surname:
        simple: ${inputs.Surname}
      tax_id:
        simple: ${inputs.Tax ID}
      vehicle_number:
        simple: ${inputs.Vehicle Number}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Retrieves ID of a data subject from passed constraints
      id: 10edcbe8-7b27-445d-8d6c-8cbbb5872b0a
      iscommand: true
      name: DataSubject id
      script: '|||inventa-get-datasubject-id'
      type: regular
      version: -1
    taskid: 10edcbe8-7b27-445d-8d6c-8cbbb5872b0a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 290
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1595,
        "width": 980,
        "x": 270,
        "y": -60
      }
    }
  }
